---
title: "Project Proposal"
author: "Name"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Provide the the following information for your project.

1. What research question(s) do you hope to answer?
2. From where did you obtain the data you will use to answer your research question?
3. How many observations does your data set have?
4. Are you merging multiple data sets?
5. Provide a table listing each variable you are considering for analysis, briefly describe each variable (e.g., the number of disease cases in each region), and the variable type (e.g., numeric, factor, date, etc.).
6. What will your response variable be for answering the research question(s)?
7. Provide a numeric summary of your response variable.
8. Provide a visual summary of your response variable (histogram if discrete, density plot if continuous, bar plot if categorical.)
9. Provide an appropriate graphical summary for each predictor variable.
